### ISSUE TITLE
Mirador 3 launch checklist

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador-website#8]
## Homepage
 - [ ] Update feature lists and copy
 - [x] Migrate M2 docs and link
 - [x] Embed an m3
 - [ ] Setup demo links
 - [x] Update hero background image
 - [x] Update participation and open source

**Comment by marlo-longley** [comment]
Closing as stale <3
